import React, {useEffect} from 'react'
import {Link} from 'react-router-dom'
import Footer from '../components/Footer'
import gb from '../images/gravity_brain_logo.svg'
const Privacy = () => {

  useEffect(() =>{
    window.scroll(0,0)
  })
  return (
    <div>
        <div className='grid grid-cols-2 items-center bg-blue-600 py-4'>
            <div>
            <Link to='/'><img src={gb} alt='logo' className='md:h-16 h-10 ml-2 md:ml-20'></img></Link>
            </div>
            <div className='text-right mb-4 md:mr-12 '>
            <Link to='/olympiad2022'><button className='md:px-6 md:py-2 px-4 py-2 text-sm md:text-lg bg-white mt-6 mr-8 text-blue-500 font-semibold rounded-lg'>Olympiad 2022</button></Link>
            </div>
        </div>

        <div className='md:mx-24 mx-4'>
            <h1 className='text-3xl mt-6 font-bold'>Privacy & Policy</h1>
            <p className='mt-3'>GravityBrain values your trust. In order to honor that trust, GravityBrain adheres to ethical standards in gathering, using, and safeguarding any information you provide.</p>
            <h1 className='text-xl mt-4 font-bold'>Introduction</h1>
            <p className='mt-3 leading-12'>GravityBrain (together with its subsidiaries, and international affiliates, hereinafter "GravityBrain," "us," "we," or "our" or "the Company") is committed to security and management of personal data, to function effectively and successfully for the benefit of our stakeholders, customers and for the community. In doing so, it is essential that people's privacy is protected through the lawful and appropriate means for handling the personal data. Therefore, we have implemented this privacy policy (hereinafter referred to as 'policy’’).</p>
            <h1 className='text-xl mt-4 font-bold'>Aim</h1>
            <p className='mt-3 leading-12'>This policy aims to protect personal data of the various stakeholders connected to our organization. This policy is aimed at providing individuals notice of the basic principles by which the company processes the personal data of individuals ("Personal Data") who visits, uses, deals with and/or transacts through the website and includes a guest user and browser (hereinafter 'you', 'user').</p>
            <h1 className='text-xl mt-4 font-bold'>Purpose and Scope</h1>
            <p className='mt-3 leading-12'>The purpose of this policy is to describe how GravityBrain collects, uses, and shares information about you through our online interfaces (e.g., websites and mobile applications) owned and controlled by us, including but not limited to https://www.GravityBrain.org/ (hereinafter the 'website'). This policy is also designed to provide information on how GravityBrain ensures data security, conducts data transfers and process requests from data subjects.</p>
            <p className='mt-3 leading-12'>This policy control applies to all systems, people and processes that constitute the organization's information systems, including board members, directors, employees and other third parties who have access to Personal Data available within GravityBrain.</p>
            <p className='mt-3 leading-12'>The company is also committed to ensure that its employees conduct themselves in line with this, and other related, policies.</p>
            <h1 className='text-xl mt-4 font-bold'>Information We Collect</h1>
            <p className='mt-3 leading-12'>We are committed to respecting your online privacy. We further recognize your need for proper protection and management of any personal information you share with us. We may collect the following information:</p>
            <p className='mt-3 leading-12'>a. Personally Identifiable Information such as and including but not limited to Name, Student Name, Age, Mobile Number, Email Address, and educational standards.</p>
            <p className='mt-3 leading-12'>b. Tracking Information such as, but not limited to your device IP address and Device ID when connected to the Internet. This information may include your originating URL (whether this URL is on a website or not), which URL you visit next (whether this URL is on a website or not), your computer or device browser information, and other information. information related to your interaction with the website.</p>
            <p className='mt-3 leading-12'>This privacy policy also applies to data we collect from any user who only visits the website, including, but not limited to, browsing behavior, pages viewed, etc. We also collect and store personal information that you provide from time to time on the website. We only collect and use such information from you as we deem necessary for marketing purpose and to achieve a smooth, efficient and secure experience, tailored to your needs including but not limited to:</p>
            <p className='mt-3 leading-12'>1. To activate the provision of the service you choose. 2. To enable Company to send solutions and information about updated courses directly to the user's Whats app. 3. To activate the display of the content you are interested in. 4. To communicate the necessary service-related information from time to time. 5. To enable you to receive quality customer service and data collection services. 6. To comply with applicable laws, rules and regulations.</p>
            <p className='mt-3 leading-12'>If any service you request involves a third party, information the company would reasonably require carrying out your service request may be shared with that third party. We also use your contact information to send you offers based on your past interests and activity and also to view content you like. The Company may also use contact information internally to direct service improvement efforts but must immediately delete all such information upon withdrawal of your consent to the same via the 'unsubscribe' button or by email to info@gravitybrain.com</p>
            <p className='mt-3 leading-12'>Wherever possible, we give you the option not to divulge any specific information that you would like us not to collect, store or use. You can also choose not to use certain services or features on the website and opt out of non-essential communications from the website.</p>
            <p className='mt-3 leading-12'>Furthermore, transacting over the internet carries inherent risks that can only be avoided by following our own security practices and notifying our customer service team of any suspicious activity.</p>
            <h1 className='text-xl mt-4 font-bold'>Our Use of Information</h1>
            <p className='mt-3 leading-12'>The information you provide will be used to provide and improve services for you and all users.</p>
            <p className='mt-3 leading-12'>a. To provide you with services at your request.</p>
            <p className='mt-3 leading-12'>b. To maintain internal records.</p>
            <p className='mt-3 leading-12'>c. To keep you updated about all plans & courses via whatsapp.</p>
            <p className='mt-3 leading-12'>d. To improve the services provided</p>
            <p className='mt-3 leading-12'>e. To maintain records under the provisions of laws and regulations.</p>
            <p className='mt-3 leading-12'>For further details on the nature of such communications, please refer to our Terms of Service. Furthermore, your data may be collected and stored by us for internal records.</p>
            <p className='mt-3 leading-12'>We use your tracking information such as IP address, and/or Device ID to help identify you and to collect broad demographic information and provide further services to you. We will not sell, license or trade your personal information. We will not share your personal information with others unless they act on our instructions, or we are required to do so under law.</p>
            <p className='mt-3 leading-12'>Information collected through our server logs includes users' IP addresses and pages visited; this will be used to manage the web system and troubleshoot. We also use third party analytics, tracking, optimization and targeting tools to understand how users engage with our website so that we can improve it and fulfill personalized content/advertising according to their preferences.</p>
            <h1 className='text-xl mt-4 font-bold'>Alerts</h1>
            <p className='mt-3 leading-12'>GravityBrain may alert you by email or phone (through sms/call/whatsapp) to inform you about new service offerings or other information which it perceives might be useful for you.</p>
            <h1 className='text-xl mt-4 font-bold'>How Information is collected</h1>
            <p className='mt-3 leading-12'>Before or at the time of collecting personal information, we may identify the purpose for which the information was collected. If the same is not identified to you, you have the right to ask us to explain the purpose for which the personal information was collected, pending fulfillment you are not obliged to disclose any information.</p>
            <p className='mt-3 leading-12'>We will collect and use your personal information solely to fulfill the purposes specified by us, within the scope of consent of the individual concerned or as required by law. We will only retain personal information for as long as is necessary for the fulfillment of that purpose. We will collect personal information in a lawful and fair manner and with the knowledge and consent of the individual concerned.</p>
            <p className='mt-3 leading-12'>Personal data must be relevant to the purpose for which it is used, and to the extent necessary for that purpose, must be accurate, complete and up to date.</p>
            <h1 className='text-xl mt-4 font-bold'>External Links on Website</h1>
            <p className='mt-3 leading-12'>Websites may include advertisements, hyperlinks to other websites or resources. We have no control over the websites or other resources or content available on these other websites, which are provided by companies or persons other than us. You acknowledge and agree that we are not responsible for the availability of such external sites or resources, and do not endorse any advertisements, services or other materials on or available from such websites or resources. You acknowledge and agree that we are not responsible for any loss or damage that may be incurred by you as a result of the availability of such external sites or resources, or as a result of any reliance you place on the completeness, accuracy or existence of advertisements, services., or any other material on, or available from, that website. These external third-party websites and resource providers may have their privacy policies governing the collection, storage, retention and disclosure of your personal information which you may comply with. We recommend that you enter the website and review their privacy policy.</p>
            <h1 className='text-xl mt-4 font-bold'>Confidentiality</h1>
            <p className='mt-3 leading-12'>You further acknowledge that the website may contain information which we deem to be confidential, and you may not disclose such information without our prior written consent. Your information is considered confidential and therefore will not be disclosed to any third party, unless legally required to do so to the appropriate authorities. We will not sell, share or rent your personal information to any third parties or use your email address for unsolicited mail. Any emails sent by us will only relate to the provision of the agreed services, and you have the sole discretion to request termination of such communications at any time.</p>
            <h1 className='text-xl mt-4 font-bold'>Other Information Collectors</h1>
            <p className='mt-3 leading-12'>Unless otherwise expressly stated in this Policy, this document only addresses the use and disclosure of information we collect from you. To the extent that you disclose your information to other parties, whether they are on our website or other sites across the Internet, different rules may apply to their use or disclosure of the information you disclose to them. To the extent that we use third party advertisers, they comply with their own privacy policies. Since we do not control the privacy policies of third parties, you should ask questions before disclosing your personal information to others.</p>
            <h1 className='text-xl mt-4 font-bold'>Cookies</h1>
            <p className='mt-3 leading-12'>We use data collection tools such as 'cookies' on certain pages on our website. 'Cookies' are small files placed on your hard drive that assist us in providing customized services. We also offer certain features that are only available using 'cookies'. Cookies can also help us provide information targeted to your interests. We use session cookies to ensure that you have a good experience. This cookie contains a unique number, your 'session ID', which allows our servers to recognize your computer and 'remember' what you have done on the site. The benefits of this are:</p>
            <p className='mt-3 leading-12'>a. You only need to log in once if you are navigating secure areas of the site. b. Our servers can distinguish between your computer and other users, so you can see the information you request.</p>
            <p className='mt-3 leading-12'>You can choose to accept or reject cookies by changing your browser settings if you wish. This can prevent you from taking full advantage of the website. We also use various third-party cookies for usage, behavior, analytics and preference data. Following are the different types of cookies used on websites:</p>
            <p className='mt-3 leading-12'>a. Authentication cookies: To identify a user and share the content he/she requests. b. Functionality cookies: For customized user experience and continuing progress of previous courses. c. Tracking, optimization, and targeting cookies: To capture usage metrics on devices, operating systems, browsers, etc. To capture behavioral metrics for better content delivery. To serve and suggest the most suitable service.</p>
            <h1 className='text-xl mt-4 font-bold'>Google Ananlytics</h1>
            <p className='mt-3 leading-12'>We use Google Analytics to help us understand how you use our content and find out how we can make it better. These cookies follow your progress through us, collecting anonymous data about where you came from, which pages you visited, and how long you spent on the site. This data is then stored by Google to generate reports. This cookie does not store your personal data.</p>
            <p className='mt-3 leading-12'>Information obtained from cookies about your use of the website, including your IP address, may be sent and stored by Google on its servers. Google may use this information for the purpose of evaluating your use of the website, compiling reports on website activity for us, and providing other services related to website activity and internet usage. Google may also transfer this information to third parties where required by law, or if those third parties process the information on Google's behalf. Google will not associate your IP address with any other data stored by Google. By using this website, you consent to Google's processing of data about you in the manner and for the purposes set out above.</p>
            <p className='mt-3 leading-12'>The Google website contains more information about analytics and a copy of the Google privacy policy page.</p>
            <h1 className='text-xl mt-4 font-bold'>Google Adsense</h1>
            <p className='mt-3 leading-12'>Google AdSense is a tool that allows us to deliver ads to you in exchange for revenue that is calculated on a per click or per impression basis. To do this, Google uses cookies and tracking technology to serve personalized ads to you. In this case, the following requirements are defined for you:</p>
            <p className='mt-3 leading-12'>a. Third party vendors, including Google, use cookies to serve ads based on your previous visits to our website or other websites.</p>
            <p className='mt-3 leading-12'>b. Google's use of advertising cookies enables us and our partners to serve ads to you based on their visit to our website and/or other websites on the internet.</p>
            <p className='mt-3 leading-12'>c. You can opt out of personalized advertising by visiting Ads Settings.</p>
            <p className='mt-3 leading-12'>d. All third-party advertisements on our website are for informative purposes only and we do not guarantee or assume any responsibility for the authenticity of the advertisements.</p>
            <p className='mt-3 leading-12'>e. We do not allow our competitors to advertise on our website</p>
            <p className='mt-3 leading-12'>f. You may visit links in advertisements at your own risk or choose not to accept cookies that allow third parties to display their advertisements.</p>
            <h1 className='text-xl mt-4 font-bold'>Disclosure of your Information</h1>
            <p className='mt-3 leading-12'>Information collected will not be considered sensitive if it is freely available and accessible in the public domain or provided under The Personal Data Protection Act (PDPA), any derivative regulations, or other currently applicable laws.</p>
            <p className='mt-3 leading-12'>Due to the scope of existing regulations, we cannot ensure that all of your personal communications and other personally identifiable information will never be disclosed in a manner not described in this Policy. For example (without limiting or eliminating), we may be compelled to disclose information to governments, law enforcement agencies or third parties. Therefore, although we use industry standard practices to protect your privacy, we do not promise, and you should not expect, that your personally identifiable information or personal communications will always remain confidential. However, we assure you that any disclosure of your personally identifiable information will be personally notified to you by email sent to the email address you provided.</p>
            <p className='mt-3 leading-12'>As part of our policy, we do not sell or rent personally identifiable information about you to any third party. However, the following describes some of the ways your personally identifiable information may be disclosed:</p>
            <p className='mt-3 leading-12'>a. External Service Providers: There may be several services offered by external service providers that help you use our website. If you choose to use these optional services, and while doing so, disclose information to external service providers, and/or allow them to collect information about you, their use of your information is governed by their privacy policies.</p>
            <p className='mt-3 leading-12'>b. Law Enforcement and Public Order: We cooperate with law enforcement investigations, as well as other third parties to enforce laws, such as intellectual property rights, fraud and other rights. We may (and you allow us to) disclose any information about you to law enforcement and other government officials because we, in our sole discretion, believe it is necessary or appropriate, in connection with an investigation of fraud, intellectual property infringement, or other illegal activity or could expose our legal responsibilities.</p>
            <h1 className='text-xl mt-4 font-bold'>Security</h1>
            <p className='mt-3 leading-12'>We treat data as an asset that must be protected from loss and unauthorized access. We use many different security techniques to protect this data from unauthorized access by members inside and outside the company. We follow generally accepted industry standards to protect the Personal Information sent to us and the information we have access to</p>
            <p className='mt-3 leading-12'>However, as effective as encryption technology is, no security system is impenetrable. Our company cannot guarantee the security of our database, nor can guarantee that the information you provide will not be intercepted when sent to the company via the internet.</p>
            <h1 className='text-xl mt-4 font-bold'>Separation</h1>
            <p className='mt-3 leading-12'>Each paragraph of this policy will remain separate from; and independent of; and may be separated from all and other paragraphs herein, unless expressly indicated or contextually indicated in this agreement. The decision or declaration that one or more paragraphs are null, and void shall not affect the other paragraphs of this privacy policy.</p>
            <h1 className='text-xl mt-4 font-bold'>Amendment</h1>
            <p className='mt-3 leading-12'>Our policies may change from time to time. The most recent version of the policy will govern our use of your information and will always be on the website. Any changes to this policy will be deemed acceptable by you on your continued use of the website.</p>
            <h1 className='text-xl mt-4 font-bold'>Revocation of Consent, Request for Data Download & Data Deletion</h1>
            <p className='mt-3 mb-6 leading-12'>To withdraw your consent, or to request a download or delete your data for any or all of our services at any time, please email info@gravitybrain.com.</p>
            
        </div>
        <Footer/> 
    </div>
  )
}

export default Privacy