import React, {useEffect} from 'react'
import {Link} from 'react-router-dom'
import Footer from '../components/Footer'
import gb from '../images/gravity_brain_logo.svg'
const Terms = () => {

    useEffect(() =>{
        window.scroll(0,0)
    })
  return (
    <div>
        <div className='grid grid-cols-2 items-center bg-blue-600 py-4'>
            <div>
            <Link to='/'><img src={gb} alt='logo' className='md:h-16 h-10 ml-2 md:ml-20'></img></Link>
            </div>
            <div className='text-right mb-4 md:mr-12 '>
            <Link to='/olympiad2022'><button className='md:px-6 md:py-2 px-4 py-2 text-sm md:text-lg bg-white mt-6 mr-8 text-blue-500 font-semibold rounded-lg'>Olympiad 2022</button></Link>
            </div>
        </div>
        <div className='md:mx-24 mx-4'>
            <h1 className='text-3xl mt-6 font-bold'>AGREEMENT TO TERMS</h1>
            <p className='mt-3 leading-12'>These Terms & Conditions (“Terms”) of (a) use of our website www.gravitybrain.com (“Website”), or any products or services in connection with the Website/products (“Services”) or (b) any modes of registrations or usage of products, are between GravityBrain Challenge (“Company/GB/We/Us/Our”) and its users (“User/You/Your”).</p>
            <p className='mt-3 leading-12'>Please read the Terms and Conditions and the Privacy Policy of the Company with respect to registration with us, the use of the Website, Services and products carefully before using the Website, Services or products. In the event of any discrepancy between the Terms and any other policies with respect to the Website or Services or products, the provisions of the Terms shall prevail.</p>
            <p className='mt-3 leading-12'>Your use/access/browsing of the Website or the Services or products or registration (with or without payment/with or without subscription) through any means shall signify Your acceptance of the Terms and Your agreement to be legally bound by the same.</p>
            <p className='mt-3 leading-12'>If You do not agree with the Terms and Conditions or the Privacy Policy, please do not use the Website or avail the Services or products. Any access to our Website/Services/products through registrations/subscription is non transferable.</p>
            <p className='mt-3 leading-12'>Except as mentioned below, all information, content, material, trademarks, services marks, trade names, and trade secrets including but not limited to the software, text, images, graphics, video, script and audio, contained in the Website, Services and products are proprietary property of the Company (“Proprietary Information”). No Proprietary Information may be copied, downloaded, reproduced, modified, republished, uploaded, posted, transmitted or distributed in any way without obtaining prior written permission from the Company and nothing on this Website or Services shall be or products deemed to confer a license of or any other right, interest or title to or in any of the intellectual property rights belonging to the Company, to the User. You may own the medium on which the information, content or materials resides, but the Company shall at all times retain full and complete title to the information, content or materials and all intellectual property rights inserted by the Company on such medium. Certain contents on the Website may belong to third parties. Such contents have been reproduced after taking prior consent from said party and all rights relating to such content will remain with such third party. Further, you recognize and acknowledge that the ownership of all trademarks, copyright, logos, service marks and other intellectual property owned by any third party shall continue to vest with such party and You are not permitted to use the same without the consent of the respective third party.</p>
            <p className='mt-3 leading-12'>i. Your use of our products, Website, Services and products is solely for your personal and non-commercial use. Any use of the Website, Services or products or their contents other than for personal purposes is prohibited. Your personal and non-commercial use of this Website, products and / or our Services shall be subjected to the following restrictions:</p>
            <p className='mt-3 leading-12'>ii. You may not decompile, reverse engineer, or disassemble the contents of the Website and/or Services/ products or modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell any information or software obtained from our Website and/or Services/products, or remove any copyright, trademark registration, or other proprietary notices from the contents of our Website and/or Services/products.</p>
            <p className='mt-3 leading-12'>a. You will not (a) use our Website and/or any of our product/s or Service/s for commercial purposes of any kind, or (b) advertise or sell any products, Services or domain names or otherwise (whether or not for profit), or solicit others (including, without limitation, solicitations for contributions or donations) or use any public forum for commercial purposes of any kind, or (c) use the Website/our products and Services in any way that is unlawful, or harms the Company or any other person or entity as determined by the Company.</p>
            <p className='mt-3 leading-12'>b. No User shall be permitted to perform any of the following prohibited activities while availing our Services:</p>
            <p className='mt-3 leading-12'>a. Making available any content that is misleading, unlawful, harmful, threatening, abusive, tortuous, defamatory, libelous, vulgar, obscene, child-pornographic, lewd, lascivious, profane, invasive of another’s privacy, hateful, or racially, ethnically or otherwise objectionable;</p>
            <p className='mt-3 leading-12'>b. Stalking, intimidating and/or harassing another and/or inciting other to commit violence;</p>
            <p className='mt-3 leading-12'>c. Transmitting material that encourages anyone to commit a criminal offence, that results in civil liability or otherwise breaches any relevant laws, regulations or code of practice;</p>
            <p className='mt-3 leading-12'>d. Interfering with any other person’s use or enjoyment of the Website/Services</p>
            <p className='mt-3 leading-12'>e. Making, transmitting or storing electronic copies of materials protected by copyright without the permission of the owner, committing any act that amounts to the infringement of intellectual property or making available any material that infringes any intellectual property rights or other proprietary rights of anyone else;</p>
            <p className='mt-3 leading-12'>f. Impersonate any person or entity, or falsely state or otherwise misrepresent Your affiliation with a person or entity;</p>
            <p className='mt-3 leading-12'>g. Post, transmit or make available any material that contains viruses, Trojan horses, worms, spyware, time bombs, cancelbots, or other computer programming routines, code, files or such other programs that may harm the website/services, interests or rights of other users or limit the functionality of any computer software, hardware or telecommunications, or that may harvest or collect any data or personal information about other Users without their consent;</p>
            <p className='mt-3 leading-12'>h. Use the Services for purposes that are not permitted by: (i) these Terms; and (ii) any applicable law, regulation or generally accepted practices or guidelines in the relevant jurisdiction; or</p>
            <p className='mt-3 leading-12'>i. Violate any of the terms specified under the Terms for the use of the Website/Services/products.</p>
            <p className='mt-3 leading-12'>ii. In the preparation of the Website/Services/products and contents such as test papers and their solutions therein, every effort has been made to offer the most current, correct, and clearly expressed information possible. Nevertheless, inadvertent errors may occur. In particular, but without limiting anything here, the Company disclaims any responsibility for any errors and accuracy of the information that may be contained in the website.</p>
            <p className='mt-3 leading-12'>iii. Our Website provides Users with access to compiled educational information and related sources. Such information is provided on an As Is basis and We assume no liability for the accuracy or completeness or use or non-obsolescence of such information. We shall not be liable to update or ensure continuity of such information contained on the Website. The Company operates on its own and is not affiliated to any other Olympiad bodies worldwide.</p>
            <p className='mt-3 leading-12'>iv. The contents of the Services/products are developed on the concepts covered in the structured curriculum syllabus prescribed for students of various courses. These are designed by subject matter experts.The Company acknowledges that there are various means of delivering structured curriculum pedagogy and inclusion of methods in the Website/Services/products does not imply endorsement of any particular method nor exclusion imply disapproval. Subscription to the website or usage of our Services/Website/products does not in any manner guarantee admission to any educational institutions or passing of any exams or achievement of any specified percentage of marks in any examinations.</p>
            <p className='mt-3 leading-12'>v. Certain contents in the Services/Website/products (in particular relating to assistance in preparations for administrative services) may contain opinions and views. The Company shall not be responsible for such opinions or any claims resulting from them. Further, the Company makes no warranties or representations whatsoever regarding the quality, content, completeness, or adequacy of such information and data.</p>
            <p className='mt-3 leading-12'>vi. Some parts of the Services are interactive, and we encourage contributions by Users, which may or may not be subject to editorial control prior to being posted.</p>
            <p className='mt-3 leading-12'>vii. The Company may, based on any form of access to the website (including free download/trials) or Services or Website or registrations through any source whatsoever, contact the User through sms, email and call, to give information about its products as well as notifications on various important updates and/or to seek permission for demonstration of its products. The User expressly grants such permission to contact him/her through telephone, SMS, e-mail and holds the Company indemnified against any liabilities including financial penalties, damages, expenses in case the User’s mobile number is registered with Do not Call (DNC)/ Do not Disturb (DND) database. By registering yourself , you agree to make your contact details available to Our employees, associates and partners so that you may be contacted for education information and promotions through telephone, SMS, email etc.</p>
            <p className='mt-3 leading-12'>viii. While the Company may, based on the User’s confirmation, facilitate the demonstration of its products at the location sought by the User, the User acknowledges that he/she has not been induced by any statements or representations of any person with respect to the quality or conditions of the products and that User has relied solely on the investigations, examinations and inspections as the User has chosen to make and that the Company has afforded the User the opportunity for full and complete investigations, examinations and inspections.</p>
            <p className='mt-3 leading-12'>ix. contact You through the registered mobile number or e-mail or any other mobile number or contact number or email provided by You to enable effective provision of Services. The User expressly permits the Company to contact him/her and the student utilising the Services, through the above mentioned means at any time post registration. Further, the Company shall have the right to monitor the download and usage of the Website/Services/products and the contents thereof by the User/student, to analyze such usage and discuss the same with the User/student to enable effective and efficient usage of the Services.</p>
            <p className='mt-3 leading-12'>x. While the Company has made efforts to train the personnel engaged in the sales and services relating to its products to enable quality control, it makes no warranties or representations whatsoever regarding the quality and competence of such personnel and would not be responsible for any deviant behaviour of any such personnel. Any feedback from User relating to the same is most welcome and Company reserves the right and discretion to take any action in this regard.</p>
            <p className='mt-3 leading-12'>xi. Access to certain elements of the Services including training, mentoring services etc may be subject to separate terms, conditions and fair usage policy. The Company reserves the right to determine the criteria for provision of various elements of Services to the different categories of Users based on its policies.</p>
            <p className='mt-3 leading-12'>xiii. The Company shall have no responsibility for any loss or damage caused to tablet or any other hardware and / or software and/or instrument, including loss of data or effect on the processing speed, resulting from Your use of our products and Services.</p>
            <p className='mt-3 leading-12'>xiv. Scholarship and Merchandise : The website will describe the accolades conferred on the deserving students There would be 2 components of accolades conferred A) Student will get free nurture program for 1 year and B) Student will be recieving goodies and merchandise from GraivtyBrain.</p>
            <p className='mt-3 leading-12'>xv. In case of physical delivery of any product, you have to specify the address to which the shipment has to be made at the time of purchase. All product(s) shall be delivered directly to the address as specified at the point of ordering and you cannot, under any circumstances whatsoever, change the address after the order is processed. In case of any change in the address, you need to specify the same to us in writing well in advance of the shipping date.</p>
            <p className='mt-3 leading-12'>xvii. In order to access the Services and to avail the use of the website/products, You shall be required to register yourself with the website/Services/products, and maintain an account with the website/Services/products. You will be required to furnish certain information and details, including Your name, mobile number, e-mail address, residential address, grade/class of the student, school name, payment information (credit/debit card details) if required, and any other information deemed necessary by the website/service/product. With respect to the provision of information, the following may be noted:- It is Your sole responsibility to ensure that the account information provided by You is accurate, complete and latest.</p>
            <p className='mt-3 leading-12'>xviii. Persons who are minors, un-discharged insolvents etc. are not eligible to register for Our products or Services. As a minor if you wish to use Our products or Services, such use shall be made available to you by your legal guardian or parents, who has agreed to these Terms. In the event a minor utilizes the Website/Services/Products, it is assumed that he/she has obtained the consent of the legal guardian or parents and such use is made available by the legal guardian or parents. The Company will not be responsible for any consequence that arises as a result of misuse of any kind of Our Website or any of Our products or Services that may occur by virtue of any person including a minor registering for the Services/products provided.</p>
            <p className='mt-3 leading-12'>• You agree to defend, indemnify and hold harmless the Company, its officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney’s fees) arising from: (i) Your use of and access of the Website/Services/Products ; (ii) Your violation of any term of these Terms or any other policy of the Company; (iii) Your violation of any third party right, including without limitation, any copyright, property, or privacy right; or (iv) any claim that Your use of the Website/Services/Products has caused damage to a third party. This defense and indemnification obligation will survive these Terms.</p>
            <p className='mt-3 leading-12'>• In no event shall the Company, its officers, directors, employees, partners or agents be liable to You or any third party for any special, incidental, indirect, consequential or punitive damages whatsoever, including those resulting from loss of use, data or profits or any other claim arising out, of or in connection with, Your use of, or access to, the Website.</p>
            <p className='mt-3 leading-12'>• In the event of Your breach of these Terms, You agree that the Company will be irreparably harmed and may not have an adequate remedy in money or damages. The Company therefore, shall be entitled in such event to obtain an injunction against such a breach from any court of competent jurisdiction. The Company’s right to obtain such relief shall not limit its right to obtain other remedies.</p>
            <p className='mt-3 leading-12'>• Any violation by You of the terms of this Clause may result in immediate suspension or termination of Your Accounts apart from any legal remedy that the Company can avail. In such instances, the Company may also disclose Your Account Information if required by any Governmental or legal authority. You understand that the violation of these Terms could also result in civil or criminal liability under applicable laws.</p>
            <p className='mt-3 leading-12'>• The Company has the right to change modify, suspend, or discontinue and/or eliminate any aspect(s), features or functionality of the Website or the Services as it deems fit at any time without notice. Further, the Company has the right to amend these Terms from time to time without prior notice to you. The Company makes no commitment, express or implied, to maintain or continue any aspect of the Website/Services/Products. You agree that the Company shall not be liable to You or any third party for any modification, suspension or discontinuance of the Website/Services/Products. All prices are subject to change without notice.</p>
            <p className='mt-3 leading-12'>• General Provisions: All notices served by the Company shall be provided via email to Your account or as a general notification on the website. Any notice to be provided to the Company should be sent to info@gravitybrain.org</p>
            <h1 className='text-xl mt-4 font-bold'>Entire Agreement:</h1>
            <p className='mt-3 leading-12'>The Terms, along with the Privacy Policy, and any other guidelines made applicable to the website from time to time, constitute the entire agreement between the Company and You with respect to Your access to or use of the Website, products and the Services thereof.</p>
            <h1 className='text-xl mt-4 font-bold'>Assignment:</h1>
            <p className='mt-3 leading-12'>You cannot assign or otherwise transfer Your obligations under the Terms, or any right granted hereunder to any third party. The Company’s rights under the Terms are freely transferable by the Company to any third parties without the requirement of seeking Your consent.</p>
            <h1 className='text-xl mt-4 font-bold'>Severability:</h1>
            <p className='mt-3 leading-12'>If, for any reason, a court of competent jurisdiction finds any provision of the Terms, or portion thereof, to be unenforceable, that provision shall be enforced to the maximum extent permissible so as to give effect to the intent of the parties as reflected by that provision, and the remainder of the Terms shall continue in full force and effect.</p>
            <h1 className='text-xl mt-4 font-bold'>Waiver:</h1>
            <p className='mt-3 leading-12'>Any failure by the Company to enforce or exercise any provision of the Terms, or any related right, shall not constitute a waiver by the Company of that provision or right.</p>
            <h1 className='text-xl mt-4 font-bold'>Relationship:</h1>
            <p className='mt-3 leading-12'>You acknowledge that your participation on the website does not make You an employee or agency or partnership or joint venture or franchise of the Company. The Company provides these Terms so that You are aware of the terms that apply to your use of the Website/Products and Services. You acknowledge that, the Company has given You a reasonable opportunity to review these Terms and that You have agreed to them.</p>
            <h1 className='text-xl mt-4 font-bold'>Refund Policy:</h1>
            <p className='mt-3 leading-12'>There is no refund for any physical product purchased, such as merchandise. Any online product purchased on www.gravitybrain.org is refundable within 24 hours and subject to the conditions noted below.</p>
            <p className='mt-3 leading-12'>i. No portion of the Courseware purchased has been accessed and attempted. In case any part of the practice Courseware has been attempted, the Courseware standalone fees will be deducted from the overall Purchase Amount</p>
            <p className='mt-3 leading-12'>ii. The student has not taken the Round for which he/she has registered If all criteria are met, submit your refund request in writing via e-mail to info@gravitybrain.org. Do mention the Registration Number of the student in the Subject of the email Requested refunds that are approved may take up to 15 business days to reflect in your account. Refunds will only be issued to the same payment method used during the initial purchase.</p>
            <h1 className='text-xl mt-4 font-bold'>Feedback:</h1>
            <p className='mt-3 leading-12'>Any feedback You provide with respect to the website shall be deemed to be non-confidential. The website shall be free to use such information on an unrestricted basis. Further, by submitting the feedback, You represent and warrant that (i) Your feedback does not contain confidential or proprietary information of You or of third parties; (ii) the Company is not under any obligation of confidentiality, express or implied, with respect to the feedback; (iii) the website may have something similar to the feedback already under consideration or in development; and (iv) You are not entitled to any compensation or reimbursement of any kind from the Company for the feedback under any circumstances, unless specified.All feedbacks are to be sent to info@gravitybrain.org Under no circumstances shall the Company be held responsible in any manner for any content provided by other users even such content is hurtful or offensive. Please exercise caution while accessing the website.</p>
            <h1 className='text-xl mt-4 font-bold'>Customer Care:</h1>
            <p className='mt-3 leading-12 pb-10'>We make all best endeavors to provide You with a pleasant experience. In the unlikely event that You face any issues, please contact us at info@gravitybrain.org</p>

        </div>
        <Footer/>
    </div>
  )
}

export default Terms